### PR TITLE
Practical 8 Tests

### PR DESCRIPTION
**Pull request by devosray**
Made a few basic tests for Task 1 & 2 of Practical 8. Mostly pushing to get a working structure for adding tests for Task1 and Task2.

Sidenote: How can I create a pull request to a new branch? Seems like I can only push to your master?

### CODE REVIEW

**Comment by devosray** [comment]
I'm done with Prac 8. I think the questions are very simple to do and that the tests are sufficient and ready to merge.

**Review by egeldenhuys — APPROVED** [review]
Looks good :+1:

**Comment by egeldenhuys** [comment]
> Sidenote: How can I create a pull request to a new branch? Seems like I can only push to your master?

The repo owner has to create and change the base branch for the pull request.

In the future we might implement a review process where at least two people get full marks using the tests before merging into master.

Thank you for the tests @devosray, will be merging into master.

**Comment by Quantum-Sicarius** [comment]
Excellent work @devosray! @egeldenhuys I think that is a good idea :+1:

**Pull request merged**
