### PR TITLE
[WIP] Assignment 1

### LINKED ISSUE #6: Use a proper test framework
Using something like Catch will allow tests to run without aborting on a failed test.

https://github.com/philsquared/Catch

### PR DESCRIPTION
**Pull request by egeldenhuys**
Tests for Assignment 1 - Task 2. 
Please test your code using these tests and post your feedback on this Pull Request.
You are encouraged to fork this repo, write your own tests or make fixes, and then sending a pull request to the `assignment1` branch.

I have not yet uploaded my code to fitchfork, therefore the validity of these tests are not yet confirmed.

**TODO:**
- [x] Update master README with new instructions
- [x] Archive prac3 tests and instructions

Fixes: #6, #10

### CODE REVIEW

**Comment by devosray** [comment]
What happens when the user has a makefile in the source directory already? Is is possible to have a separate "debug" makefile?

I know a lot of big projects have a 
`./configure` 
script to generate the makefile. Maybe we can look into this to auto generate the `$(BLACK-FITCH-SRC)` variable?

**Comment by egeldenhuys** [comment]
I will write a script stored in the assignment 1 folder to generate a makefile that points to the black-fitch repo. It will have a name such as `makefile_black-fitch`

Which can then be copied to the user source directory and used with `make -f <makefile> <target>`

**Comment by egeldenhuys** [comment]
**makefile:**

``` makefile
Hobbit.o: Hobbit.cpp Hobbit.h
    g++ -std=c++11 -static -c Hobbit.cpp

Wizard.o: Wizard.cpp Wizard.h
    g++ -std=c++11 -static -c Wizard.cpp

Spell.o: Spell.cpp Spell.h
    g++ -std=c++11 -static -c Spell.cpp

main: Spell.o Wizard.o Hobbit.o main.cpp
    g++ -std=c++11 -static Spell.o Wizard.o Hobbit.o main.cpp -o main

run: main
    ./main

clean:
    rm -f *.o *.out main
```

**fitchfork:**

```
Compile FAILURE => Cannot find executable 'main'

EXCEPTION raised trying to run assignment: Executable not set
This is due to the WARNINGS, ERRORS and/or FAILURES shown above, which you have to fix before continuing.
```

I suspect it is the `clean` target I forgot at the end.

Will submit without the clean rule once the tests have been run against other people's source

**Comment by egeldenhuys** [comment]
Task 3 (35/35):

```
Your ostream operator is working correctly.
Your pre-increment operator is working correctly.
Your post-increment operator is working correctly.
Your pre-decrement operator is working correctly.
Your post-decrement operator is working correctly.
Your -= operator is working correctly.
Your assignment operator is working correctly.
```

**Comment by egeldenhuys** [comment]
Task 2 (8/20):

```
Your addItem and getItem function is working correctly.
Your less than operator is incorrect.
Your less than operator is working correctly.
Your greater than operator is incorrect.
Your + operator is incorrect.
Your - operator is working correctly.
```

**Comment by egeldenhuys** [comment]
Task 4 (3/4):

```
Your hasBeenSummoned function is working correctly.
Your hasCompletedTraining function is working correctly.
Your dropWizardSpell function is incorrect. Are you dealing with spells in the correct way?
```

**Pull request merged**
