### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by egeldenhuys**
Please post your fitchfork results or any problems here after testing with black-fitch.

### CODE REVIEW

**Comment by ghost** [comment]
gives me -1 when uploading to Fitch-fork

```
Compile WARNING => Possible compile warnings and/or errors follow, try to get rid of them.
main.cpp: In function 'int main()':
main.cpp:66:9: error: 'SubstitutionCipher' is an inaccessible base of 'OneTimePad'
   trans = &pad;
         ^
main.cpp:75:10: error: 'Cipher' is an inaccessible base of 'OneTimePad'
   cipher = &pad;
          ^
makefile:8: recipe for target 'main.o' failed
make: *** [main.o] Error 1

Compile FAILURE

EXCEPTION raised trying to run assignment: Executable not set
This is due to the WARNINGS, ERRORS and/or FAILURES shown above, which you have to fix before continuing.
```

**Comment by egeldenhuys** [comment]
@Paulo-W, I recreated the fitchfork test case using

``` c++
    OneTimePad pad(5);

    SubstitutionCipher *sub;
    Cipher *cipher;

    sub = &pad;
    cipher = &pad;
```

The compile error is caused when `OneTimePad` does not inherit as `public` from `Caesar`:

``` c++
class OneTimePad : public Caesar
```

I will add this test case to black-fitch. Thank you for posting the error.

**Comment by ghost** [comment]
Thank you for the help!!!!
fitchfork has zero complaints :smiling_imp:

**Comment by egeldenhuys** [comment]
Fitchfork results for Task1:

```
20/20

Success: resetting default shift value
Success: caesar (small shift), direct access
Success: caesar (small shift), access via SubstitutionCipher
Success: caesar (small shift)
Success: one-time pad, direct access
Success: one-time pad, access via SubstitutionCipher
Success: one-time pad, access via Cipher

Success: setShift (bounds checking)
Success: caesar (large shift), direct access
Success: caesar (large shift), access via SubstitutionCipher
Success: caesar (large shift), access via Cipher
Success: one-time pad
Success: one-time pad, access via SubstitutionCipher
Success: one-time pad, access via Cipher

Success: setShift (bounds checking)
Success: caesar
Success: one-time pad
```

**Comment by egeldenhuys** [comment]
Fitchfork results for Task 2:

```
20/20

Success: rows-columns, full matrix
Success: exception handling on full matrix
Success: zig-zag, full matrix
Success: exception handling on full matrix (zig-zag)
Success: encode zig-zag text with rows-columns

Success: rows-columns, under-full matrix
Success: exception handling on under-full matrix
Success: zig-zag, full matrix
Success: exception handling on under-full matrix (zig-zag)
Success: encode zig-zag text with rows-columns

Success: rows-columns, under-full matrix
Success: exception handling on under-full matrix
Success: zig-zag, full matrix
Success: exception handling on under-full matrix (zig-zag)
Success: encode zig-zag text with rows-columns
```

**Comment by egeldenhuys** [comment]
Fitchfork results for task 3:

```
20/20

Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline encode: =, +
Success: cipher pipeline decode: =, +
Success: cipher pipeline encode: +=, +
Success: cipher pipeline decode: +=, +

Success: caesar error handling
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, =, +
Success: cipher pipeline encode: +=, +
Success: cipher pipeline decode: +=, +

Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, +=
Success: cipher pipeline, =, +
Success: cipher pipeline, +=, +
```

**Comment by egeldenhuys** [comment]
Closes #29, #23

**Pull request merged**
